const { DataTypes } = require("sequelize");
const { element } = require('../config/db');

  const AssementForm = element.define(
    "AssementForm",
    {
      id: {
        type: DataTypes.DECIMAL(18, 0),
        autoIncrement: true,
      },
      requisition_no: { type: DataTypes.STRING(50), primaryKey: true},
      name: { type: DataTypes.STRING(500) },
      mobile: { type: DataTypes.STRING(50) },
      email: { type: DataTypes.STRING(100) },
      pincode: { type: DataTypes.STRING(50) },
      sale: { type: DataTypes.STRING(50) },
      outletname: { type: DataTypes.STRING(500) },
      outletcode: { type: DataTypes.STRING(50) },
      channel: { type: DataTypes.STRING(50) },
      designation: { type: DataTypes.STRING(500) },
      division: { type: DataTypes.STRING(500) },
      reginaloffice: { type: DataTypes.STRING(500) },
      experience: { type: DataTypes.STRING(50) },
      offerctc: { type: DataTypes.DECIMAL(18, 2) },
      lastctc: { type: DataTypes.DECIMAL(18, 2) },
      hike: { type: DataTypes.DECIMAL(18, 2) },
      iclevelfirst: { type: DataTypes.STRING(500) },
      iclevelsecond: { type: DataTypes.STRING(500) },
      date: { type: DataTypes.DATE },
      status: { type: DataTypes.STRING(50) },
      remarks: { type: DataTypes.STRING(500) },
      productknow: { type: DataTypes.STRING(500) },
      communication: { type: DataTypes.STRING(500) },
      sellingskills: { type: DataTypes.STRING(500) },
      personality: { type: DataTypes.STRING(500) },
      attitude: { type: DataTypes.STRING(500) },
      totalresult: { type: DataTypes.STRING(500) },
      result_status: { type: DataTypes.STRING(500) },
      RemarkbyRM: { type: DataTypes.STRING(500) },
      RMCode: { type: DataTypes.STRING(50) },
      adhaarmsg: { type: DataTypes.STRING(500) },
      enteraadhaarnumber: { type: DataTypes.STRING(50) },
      uanmessage: { type: DataTypes.STRING(500) },
      uannumber: { type: DataTypes.STRING(50) },
      orgUnitCode: { type: DataTypes.STRING(255) },
      profileCode: { type: DataTypes.STRING(255) },
      departmentCode: { type: DataTypes.STRING(255) },
      designationCode: { type: DataTypes.STRING(255) },
      saleOfficeCode: { type: DataTypes.STRING(255) },
      rmManager: { type: DataTypes.STRING(200) },
      doj: { type: DataTypes.DATE },
      bg_remarks: { type: DataTypes.STRING(250) },
      bg_status: { type: DataTypes.STRING(250) },
      bg_date: { type: DataTypes.DATE },
      rmsfaId: { type: DataTypes.STRING(255) },
      sourceName: { type: DataTypes.STRING(255) },
      updatedCurrentCtc: { type: DataTypes.STRING(255) },
      updatedLastCtc: { type: DataTypes.STRING(255) },
      workLocation: { type: DataTypes.STRING(255) },
      statusDate: { type: DataTypes.STRING(100) },
      requisition: { type: DataTypes.STRING(250) },
      dob: { type: DataTypes.DATE },
      isreinstate: { type: DataTypes.BOOLEAN },
      orgType: { type: DataTypes.STRING(250) },
      dept: { type: DataTypes.STRING(250) },
      subDept: { type: DataTypes.STRING(250) },
      sourceType: { type: DataTypes.STRING(250) },
      divisionCode: { type: DataTypes.STRING(250) },
      qualification: { type: DataTypes.STRING(250) },
      repDetails: { type: DataTypes.TEXT }, // nvarchar(max)
      secondLevelApp: { type: DataTypes.STRING(250) },
      secondLevelAppRemarks: { type: DataTypes.STRING(500) },
      secondLevelAppDate: { type: DataTypes.DATE },
      bloodGroup: { type: DataTypes.STRING(50) },
      maritalStatus: { type: DataTypes.STRING(150) },
      fatherName: { type: DataTypes.STRING(200) },
      gender: { type: DataTypes.STRING(100) },
      nationality: { type: DataTypes.STRING(150) },
      panNo: { type: DataTypes.STRING(20) },
      spouseName: { type: DataTypes.STRING(100) },
      hfinalstatus: { type: DataTypes.STRING(150) },
      hfinalremarks: { type: DataTypes.STRING(150) },
      hfinaldate: { type: DataTypes.DATE },
      hinalstatus1: { type: DataTypes.STRING(200) },
      hinalremarks1: { type: DataTypes.STRING(200) },
      hfinaldate1: { type: DataTypes.DATE },
      repEmpId: { type: DataTypes.STRING(250) },
      isSubmit: { type: DataTypes.BOOLEAN },
      subPosition: { type: DataTypes.STRING(255) },
    },
    {
      tableName: "Assesment_Form",
      timestamps: false,
    }
  );

module.exports = AssementForm;
